apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
type: Opaque
data: 
# these are only encoded any one can decode easily so that use aws ssm parameters to store secrets
  username: ZWMyLXVzZXIK
  password: RGV2T3BzMzIxCg==